@startuml
'https://plantuml.com/class-diagram

Log --* Task
DayLog --* Log

enum TaskType {
    RESEARCH
    CODING
    DESIGN
}

class Task {
    - String description

    + Task(String description)
}

class Log {
    - LocalDateTime dateTime
    - ArrayList<Task> tasks

    + Log(ArrayList<TasK> tasks
}

class DayLog {
    - ArrayList<Log> logs

    + DayLog(ArrayList<Log> logs)
}

@enduml